name: Alerta BTC

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar biblioteca
        run: pip install requests

      - name: Executar alerta
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alerta_btc.py
